name: 'Get docker images for submodules'
description: 'Retrieve all images, defined by the submodules config.json.'
author: stefan.wiedemann@fiware.org
branding:
  icon: 'tag'
  color: 'green'

inputs:
  includeVersion:
    description: 'Should the resulting image include its released versions.'
    required: false
    default: "true"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INCLUDE_VERSION: ${{ inputs.includeVersion }}